net:
	cd libnet && make ../../resources/libnet.dylib

reddit:
	cd libreddit/java && make libreddit.dylib
	cp libreddit/java/libreddit.dylib ../resources
	mkdir -p ../java/uk/co/therhys/CReddit
	cp libreddit/java/*.java ../java/uk/co/therhys/CReddit