/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.co.therhys.CReddit;

public class CommentVector extends java.util.AbstractList<Comment> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CommentVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CommentVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libredditJNI.delete_CommentVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CommentVector(Comment[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Comment element : initialElements) {
      add(element);
    }
  }

  public CommentVector(Iterable<Comment> initialElements) {
    this();
    for (Comment element : initialElements) {
      add(element);
    }
  }

  public Comment get(int index) {
    return doGet(index);
  }

  public Comment set(int index, Comment e) {
    return doSet(index, e);
  }

  public boolean add(Comment e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Comment e) {
    modCount++;
    doAdd(index, e);
  }

  public Comment remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public CommentVector() {
    this(libredditJNI.new_CommentVector__SWIG_0(), true);
  }

  public CommentVector(CommentVector other) {
    this(libredditJNI.new_CommentVector__SWIG_1(CommentVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libredditJNI.CommentVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libredditJNI.CommentVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libredditJNI.CommentVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libredditJNI.CommentVector_clear(swigCPtr, this);
  }

  public CommentVector(int count, Comment value) {
    this(libredditJNI.new_CommentVector__SWIG_2(count, Comment.getCPtr(value), value), true);
  }

  private int doSize() {
    return libredditJNI.CommentVector_doSize(swigCPtr, this);
  }

  private void doAdd(Comment x) {
    libredditJNI.CommentVector_doAdd__SWIG_0(swigCPtr, this, Comment.getCPtr(x), x);
  }

  private void doAdd(int index, Comment x) {
    libredditJNI.CommentVector_doAdd__SWIG_1(swigCPtr, this, index, Comment.getCPtr(x), x);
  }

  private Comment doRemove(int index) {
    long cPtr = libredditJNI.CommentVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Comment(cPtr, false);
  }

  private Comment doGet(int index) {
    long cPtr = libredditJNI.CommentVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Comment(cPtr, false);
  }

  private Comment doSet(int index, Comment val) {
    long cPtr = libredditJNI.CommentVector_doSet(swigCPtr, this, index, Comment.getCPtr(val), val);
    return (cPtr == 0) ? null : new Comment(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libredditJNI.CommentVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
