/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.co.therhys.CReddit;

public class libreddit {
  public static Post process_post(Reddit reddit, SWIGTYPE_p_cJSON child) {
    long cPtr = libredditJNI.process_post(Reddit.getCPtr(reddit), reddit, SWIGTYPE_p_cJSON.getCPtr(child));
    return (cPtr == 0) ? null : new Post(cPtr, false);
  }

}
