/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.co.therhys.CReddit;

public class Post {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Post(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Post obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libredditJNI.delete_Post(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTitle(String value) {
    libredditJNI.Post_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return libredditJNI.Post_title_get(swigCPtr, this);
  }

  public void setAuthor(String value) {
    libredditJNI.Post_author_set(swigCPtr, this, value);
  }

  public String getAuthor() {
    return libredditJNI.Post_author_get(swigCPtr, this);
  }

  public void setSubreddit(Subreddit value) {
    libredditJNI.Post_subreddit_set(swigCPtr, this, Subreddit.getCPtr(value), value);
  }

  public Subreddit getSubreddit() {
    long cPtr = libredditJNI.Post_subreddit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Subreddit(cPtr, false);
  }

  public void setText(String value) {
    libredditJNI.Post_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return libredditJNI.Post_text_get(swigCPtr, this);
  }

  public void setThumbnail(String value) {
    libredditJNI.Post_thumbnail_set(swigCPtr, this, value);
  }

  public String getThumbnail() {
    return libredditJNI.Post_thumbnail_get(swigCPtr, this);
  }

  public void setUrl(String value) {
    libredditJNI.Post_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return libredditJNI.Post_url_get(swigCPtr, this);
  }

  public void setUpvotes(long value) {
    libredditJNI.Post_upvotes_set(swigCPtr, this, value);
  }

  public long getUpvotes() {
    return libredditJNI.Post_upvotes_get(swigCPtr, this);
  }

  public void setDownvotes(long value) {
    libredditJNI.Post_downvotes_set(swigCPtr, this, value);
  }

  public long getDownvotes() {
    return libredditJNI.Post_downvotes_get(swigCPtr, this);
  }

  public void setScore(long value) {
    libredditJNI.Post_score_set(swigCPtr, this, value);
  }

  public long getScore() {
    return libredditJNI.Post_score_get(swigCPtr, this);
  }

  public void setId(String value) {
    libredditJNI.Post_id_set(swigCPtr, this, value);
  }

  public String getId() {
    return libredditJNI.Post_id_get(swigCPtr, this);
  }

  public void setType(String value) {
    libredditJNI.Post_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return libredditJNI.Post_type_get(swigCPtr, this);
  }

  public int get_comments(long limit, String after, SWIGTYPE_p_f_p_Comment_p_void_int__void callback, SWIGTYPE_p_void ptr) {
    return libredditJNI.Post_get_comments(swigCPtr, this, limit, after, SWIGTYPE_p_f_p_Comment_p_void_int__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(ptr));
  }

  public int get_comments_t(long limit, String after, SWIGTYPE_p_f_p_Comment_p_void_int__void callback, SWIGTYPE_p_void ptr) {
    return libredditJNI.Post_get_comments_t(swigCPtr, this, limit, after, SWIGTYPE_p_f_p_Comment_p_void_int__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(ptr));
  }

  public String fullname() {
    return libredditJNI.Post_fullname(swigCPtr, this);
  }

  public String full_url() {
    return libredditJNI.Post_full_url(swigCPtr, this);
  }

  public boolean is_img() {
    return libredditJNI.Post_is_img(swigCPtr, this);
  }

  public Post() {
    this(libredditJNI.new_Post(), true);
  }

}
