/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.co.therhys.CReddit;

public class PostVector extends java.util.AbstractList<Post> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PostVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PostVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libredditJNI.delete_PostVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PostVector(Post[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Post element : initialElements) {
      add(element);
    }
  }

  public PostVector(Iterable<Post> initialElements) {
    this();
    for (Post element : initialElements) {
      add(element);
    }
  }

  public Post get(int index) {
    return doGet(index);
  }

  public Post set(int index, Post e) {
    return doSet(index, e);
  }

  public boolean add(Post e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Post e) {
    modCount++;
    doAdd(index, e);
  }

  public Post remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public PostVector() {
    this(libredditJNI.new_PostVector__SWIG_0(), true);
  }

  public PostVector(PostVector other) {
    this(libredditJNI.new_PostVector__SWIG_1(PostVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libredditJNI.PostVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libredditJNI.PostVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libredditJNI.PostVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libredditJNI.PostVector_clear(swigCPtr, this);
  }

  public PostVector(int count, Post value) {
    this(libredditJNI.new_PostVector__SWIG_2(count, Post.getCPtr(value), value), true);
  }

  private int doSize() {
    return libredditJNI.PostVector_doSize(swigCPtr, this);
  }

  private void doAdd(Post x) {
    libredditJNI.PostVector_doAdd__SWIG_0(swigCPtr, this, Post.getCPtr(x), x);
  }

  private void doAdd(int index, Post x) {
    libredditJNI.PostVector_doAdd__SWIG_1(swigCPtr, this, index, Post.getCPtr(x), x);
  }

  private Post doRemove(int index) {
    long cPtr = libredditJNI.PostVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Post(cPtr, false);
  }

  private Post doGet(int index) {
    long cPtr = libredditJNI.PostVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Post(cPtr, false);
  }

  private Post doSet(int index, Post val) {
    long cPtr = libredditJNI.PostVector_doSet(swigCPtr, this, index, Post.getCPtr(val), val);
    return (cPtr == 0) ? null : new Post(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libredditJNI.PostVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
