/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package uk.co.therhys.CReddit;

public class SubredditVector extends java.util.AbstractList<Subreddit> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SubredditVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubredditVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libredditJNI.delete_SubredditVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SubredditVector(Subreddit[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Subreddit element : initialElements) {
      add(element);
    }
  }

  public SubredditVector(Iterable<Subreddit> initialElements) {
    this();
    for (Subreddit element : initialElements) {
      add(element);
    }
  }

  public Subreddit get(int index) {
    return doGet(index);
  }

  public Subreddit set(int index, Subreddit e) {
    return doSet(index, e);
  }

  public boolean add(Subreddit e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Subreddit e) {
    modCount++;
    doAdd(index, e);
  }

  public Subreddit remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public SubredditVector() {
    this(libredditJNI.new_SubredditVector__SWIG_0(), true);
  }

  public SubredditVector(SubredditVector other) {
    this(libredditJNI.new_SubredditVector__SWIG_1(SubredditVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libredditJNI.SubredditVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libredditJNI.SubredditVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libredditJNI.SubredditVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libredditJNI.SubredditVector_clear(swigCPtr, this);
  }

  public SubredditVector(int count, Subreddit value) {
    this(libredditJNI.new_SubredditVector__SWIG_2(count, Subreddit.getCPtr(value), value), true);
  }

  private int doSize() {
    return libredditJNI.SubredditVector_doSize(swigCPtr, this);
  }

  private void doAdd(Subreddit x) {
    libredditJNI.SubredditVector_doAdd__SWIG_0(swigCPtr, this, Subreddit.getCPtr(x), x);
  }

  private void doAdd(int index, Subreddit x) {
    libredditJNI.SubredditVector_doAdd__SWIG_1(swigCPtr, this, index, Subreddit.getCPtr(x), x);
  }

  private Subreddit doRemove(int index) {
    long cPtr = libredditJNI.SubredditVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Subreddit(cPtr, false);
  }

  private Subreddit doGet(int index) {
    long cPtr = libredditJNI.SubredditVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Subreddit(cPtr, false);
  }

  private Subreddit doSet(int index, Subreddit val) {
    long cPtr = libredditJNI.SubredditVector_doSet(swigCPtr, this, index, Subreddit.getCPtr(val), val);
    return (cPtr == 0) ? null : new Subreddit(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libredditJNI.SubredditVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
